### ISSUE TITLE
Scrapbook - Can't make clips from a conversation

### ISSUE THREAD

**Issue by alexchippendale** [kidtalkdev/KidTalkRemainingTasks#1]
Scrapbook - Can't make clips from a conversation

**Comment by alexchippendale** [comment]
@jkhartshorne This has been deployed to staging. 

You can now make snippets on the scrapbook page from any conversation tile (or picture conversation tile) by selecting the "Create Snippet" button:

<img width="333" alt="Screen Shot 2020-08-27 at 10 51 34 PM" src="https://user-images.githubusercontent.com/8966247/91526167-dcd7a280-e8b7-11ea-8304-944191251e7b.png">

This will take you to the 'make a snippet' view where you can take the original conversation and select the snippet you're interested in. You can also tag users in the snippet, provide a transcription, select icons, and mark as private:

<img width="315" alt="Screen Shot 2020-08-27 at 10 55 05 PM" src="https://user-images.githubusercontent.com/8966247/91526385-5a031780-e8b8-11ea-97ef-d32a54cfbfbe.png">

<img width="341" alt="Screen Shot 2020-08-27 at 10 56 35 PM" src="https://user-images.githubusercontent.com/8966247/91526480-90d92d80-e8b8-11ea-9cc5-75291fd47a4c.png">

Upon submitting the new snippet and navigating back to the scrapbook, the snippet will then be viewable it as a scrapbook tile, and viewable from the original conversation under the "Snippets" section (#1):

<img width="338" alt="Screen Shot 2020-08-27 at 11 00 29 PM" src="https://user-images.githubusercontent.com/8966247/91526715-1bba2800-e8b9-11ea-96ef-36bf2c309817.png">

**Comment by jkhartshorne** [comment]
1. After saving a snippet, I am returned to the "make a recording" page. Could I be returned to that conversation instead? Or to the snippet in the scrapbook? Or at least the scrapbook itself?

2. Also, what is "Clear Conversation" meant to imply in the "make a snippet" page? I worry it means "delete". 

![Screen Shot 2020-08-31 at 4 12 00 PM](https://user-images.githubusercontent.com/6118115/91764144-caee4c00-eba4-11ea-9386-5ac43fb4c29f.png)

Clicking it seems to take me to the "make a recording" page. Which is not what I'd expect. 

3. I see that "clear conversation" appears when I make a recording as well. Maybe "Cancel"?

**Comment by alexchippendale** [comment]
1. Yes we can write additional code to return to a more appropriate view such as the scrapbook when a snippet is submitted. The code for the make a snippet view is extended from the recording view, which takes you back to the recording view by default.

2. Like (1). that button is just carried over from the recording view code it's descended from. The button in the normal record view is basically just a cancel button so you can make a new recording. We will write some code to remove it for this case.

3. Yes it is essentially just a cancel button, we'll update the copy.
