### ISSUE TITLE
Importing / Recording  - For imported clips, doesn't auto-populate date from meta-data

### ISSUE THREAD

**Issue by alexchippendale** [kidtalkdev/KidTalkRemainingTasks#10]
Importing / Recording - For imported clips, doesn't auto-populate date from meta-data

**Comment by alexchippendale** [comment]
Update: Time estimate of 2-5 hours. Could be less but I anticipate some videos or imported audio will have different formats for meta data, which will require more logic than simply grabbing the key value pairs of the meta data and will need some debugging and error handling.

**Comment by alexchippendale** [comment]
We are going to try to complete this this week. If not, should be in next week.

**Comment by alexchippendale** [comment]
This has been deployed to staging. Date is now auto-populated with the meta-data from uploads.

PC / Mac / Desktop Computers / Android devices should all populate with the date you see on the file. iOS safari pre processes uploads in such a way that the date accessible to the browser from the meta-data is the date uploaded (the current date). In either case the field in the app is auto-populated with the meta-data date and the user can then edit that date if they choose.

**Comment by jkhartshorne** [comment]
Working for me!
