### ISSUE TITLE
Importing / Recording - Still need to remove the request for picking a time. Should be just date. 

### ISSUE THREAD

**Issue by alexchippendale** [kidtalkdev/KidTalkRemainingTasks#11]
Importing / Recording - Still need to remove the request for picking a time. Should be just date.

**Comment by alexchippendale** [comment]
We are working on removing the time selection requirement. This will mean multiple recordings given the same selected date will be logged as occurring at the same time and their orders will be interchangeable in the scrapbook and other parts of the app that organize by datetime. Along with this we will be removing the timestamp on tiles in the scrapbook.

**Comment by jkhartshorne** [comment]
I think that's fine.

**Comment by alexchippendale** [comment]
@jkhartshorne This has been deployed to staging.
