### ISSUE TITLE
Sharing / Family - Sharing with an adult does not give you the ability to tag that adult. 

### ISSUE THREAD

**Issue by alexchippendale** [kidtalkdev/KidTalkRemainingTasks#15]
You basically have to make two adults: one who is shared with, and one who you can tag. Their avatars may not match. Also, the system completely ignores the name you give to the person you shared with. This results in some weird behavior. 

Most intuitive would be to just automatically make anyone you are sharing with be someone you can tag. They should automatically show up in the "adults to tag in audio" list. If possible, it should just automatically use the name and avatar that the other adult chooses for themselves. But if that is annoying, then we can use the name and avatar to the sharing account chose for them. But then that means that the shared-with account will look different in the scrapbook for the sharer (using the name and avatar the sharer chose) and for the share-ee (using the name and avatar the share-ee chose).

**Comment by alexchippendale** [comment]
This is currently in development. Related to https://github.com/jkhartshorne/KidTalkIssues/issues/32

**Comment by alexchippendale** [comment]
@jkhartshorne This has been deployed to staging as well. Sharing with an adult now automatically gives you the ability to tag that adult.

**Comment by jkhartshorne** [comment]
I was about to say this doesn't work, but I think it does work ... but only with newly-added family members. Anyone you already shared with isn't included. 

Is this something we can retroactively update? If we don't, we may have people un-sharing and then re-sharing. I'm not sure if that causes problems.

**Comment by alexchippendale** [comment]
@jkhartshorne We're currently looking into what we can do for retroactive user tags from existing invites. I'll let you know what we find and what's possible once we know more.

**Comment by alexchippendale** [comment]
@jkhartshorne We are currently developing a way to take existing user tags and allow users to link them with their existing shared users on the 'My Family' page. This will be done by simply clicking the tagged user button and selecting the shared user. This will then sync up their user tags with their shared users without people needing to re-share or make further modifications. If the user they shared with has selected their own name and avatar, it will update their existing user tag appropriately. This is already deployed for new invites which will automatically create a user tag that updates whenever the invited user selects a name or avatar.

**Comment by jkhartshorne** [comment]
If this is a lot of work (more than 5 hours from this point), we can skip
it. We checked, and it won't affect many people.

**Comment by alexchippendale** [comment]
@jkhartshorne Sounds good, I think it will be less that 5 hours, if it seems like it will go over, we'll skip it.

**Comment by alexchippendale** [comment]
We've deployed the linking mechanic to staging for retroactive cases. Users can now just open up an adult tag, and if the tag isn't already linked to an invited user then they'll be able to select a user to link it to:

<img width="328" alt="Screen Shot 2020-08-29 at 3 59 31 PM" src="https://user-images.githubusercontent.com/8966247/91647526-a2354d80-ea10-11ea-86b0-09fbd9213679.png">

We will be updating staging over the next couple days with enhancements that will address related issues brought up in https://github.com/jkhartshorne/KidTalkIssues/issues/32 as well. Now sharing with an adult gives you the ability to tag that adult, and users now have the option to link a tagged adult to an invited user for retroactive cases.

**Comment by jkhartshorne** [comment]
Just checking: this has *not* been deployed to staging yet, right? Because I don't see that option yet.

![Screen Shot 2020-08-31 at 4 08 26 PM](https://user-images.githubusercontent.com/6118115/91763867-3edc2480-eba4-11ea-9d0c-68fe7fb6f063.png)

**Comment by alexchippendale** [comment]
@jkhartshorne It should show up for tagged adults that aren't already linked to an invited user. If already linked, that field is removed. Basically the field shows up for the retro active case, or with stand alone adult tags that a user later on wants to send an invitation to use the app to and link it to the tag they've been using. Going forward, new invites automatically create and link a user tag, so linking is already taken care of for them. 

Let me know if the adult tag you are testing with isn't linked already and also that there are unlinked invited users available. If that's the case, the field should show up and if it's not there could be a javascript bug or something similar.

**Comment by jkhartshorne** [comment]
I dont think they are linked. Would I be able to tell?

In any case, I made these tags and invites before linking was an option.

**Comment by alexchippendale** [comment]
Okay we're taking a look. Could you also send a screenshot of your My Family page without the edit user tag pop up? It might help us figure out what's going on.

**Comment by jkhartshorne** [comment]
![Screen Shot 2020-08-31 at 7 37 27 PM](https://user-images.githubusercontent.com/6118115/91778742-74dbd180-ebc1-11ea-9ba4-2ca4229ba091.png)

**Comment by alexchippendale** [comment]
@jkhartshorne Could you log into the account that has the first name "Ardalin"? It looks like that account and this user tag are linked. If you change the name or avatar from that account, it should change on the user tag as well when you log back into this one.
