### ISSUE TITLE
ASAP: Can we have a pop-up orienting people to the new design?

### ISSUE THREAD

**Issue by jkhartshorne** [kidtalkdev/KidTalkRemainingTasks#20]
After the app is updated, we need to warn returning users. Also, we know that new users are sometimes uncertain what to do. Can we add a one-time popup that would show the first time someone logs in after the update (whether a new user or old)? 

"Welcome to KidTalk 2.0. Click here to learn how it works."

with a link to a blog post. Please confirm we can do this, and I'll get you the link to the blog post.

**Comment by alexchippendale** [comment]
@jkhartshorne Yes that should be doable.

**Comment by jkhartshorne** [comment]
@alexchippendale - here is a permalink to the blog post: https://medium.com/@kidtalkscrapbook/august2020updates-5c57918640a0

Obviously, the post is a work-in-progress, since it depends on the updates to the app themselves!

**Comment by alexchippendale** [comment]
@jkhartshorne Thank you!

**Comment by jkhartshorne** [comment]
I don't know if this is something we can test or not? In any case, let me know when it's ready so that we can close this.

**Comment by alexchippendale** [comment]
@jkhartshorne Sounds good. We won't be deploying this until the other updates are complete correct? As in, they'll see the pop up and link to the blog post when the new features are available on production, not beforehand correct?

**Comment by jkhartshorne** [comment]
Correct. I'm not sure on our timeline for that. It sounded like you were expecting the major functionality to be ready for testing later this week?

**Comment by alexchippendale** [comment]
@jkhartshorne We'll be knocking out about half of the items from this repo this week. Others will be completed next week which should wrap up almost all of them. At that point we'll be in good position for the v2 production release which we will release with this one time pop-up orienting people to the new design.

**Comment by alexchippendale** [comment]
@jkhartshorne We've built the code for this, once the v2 is ready to go we'll deploy it to staging as the last item to test before promoting to production.

**Comment by alexchippendale** [comment]
@jkhartshorne This is deployed to staging. Let me know if you need us to change the link to the post or anything before the production release, we're using the one given above:  https://medium.com/@kidtalkscrapbook/august2020updates-5c57918640a0 .
