### ISSUE TITLE
Will changing Mailchimp Account details break the API connection?

### ISSUE THREAD

**Issue by parkerrobbins** [kidtalkdev/KidTalkRemainingTasks#21]
Hi. I would like to change the following on Mailchimp:

1. The name of the default audience from "Chip Studio" to "KidTalk Scrapbook Newsletter". (It looks like audiences are based on an arbitrary ID not the name in the API call, but I want to be sure.)

1. Change all of the basic information under https://us10.admin.mailchimp.com/account/profile/: to (1) our own email address, (2) a username that matches our KidTalk email address, and (3) and the first and last name to "KidTalk Scrapbook".

1. Change the account name from "Chip Studio" to "KidTalk Scrapbook"

1. Change all of the contact information to our own contact information.

Will any of these things affect the API connection? For example, I see the user on the API key is listed as "Hal Halperson (owner)", so I'm not sure what changing that would do.

Please let me know if you have any questions.

Thanks,

Parker

**Comment by alexchippendale** [comment]
@parkerrobbins Thank you for the detail. I will speak with the devs about the API connection and get back to you when I get a chance.

**Comment by alexchippendale** [comment]
@parkerrobbins I haven't been able to go over this fully yet, but I believe any changes to the API connection will be minimal if any are needed at all. I will be going over this tomorrow with one of the devs on the project who has more knowledge of this and will update you after that meeting to make sure.

**Comment by parkerrobbins** [comment]
@alexchippendale Thank you! 

When you speak to them, could you also ask them what they would need to set up an API connection for a second Mailchimp audience? (I'm guessing it's just the audience ID.) 

Basically we would like to have two separate mailing lists: one for a newsletter and one for a daily scrapbooking tip. Our current Mailchimp audience will become the newsletter audience, and once we have upgraded our Mailchimp plan we will create a new audience for this second list. We would like the exact same API settings for this second list as the current one.

Please let me know if you have any questions. Thanks again.

**Comment by alexchippendale** [comment]
@parkerrobbins I've learned a bit more from the meeting. The main thing is just to not reset the API key itself. You should be able to change the other stuff without changing the API connection. 

For the 2 audiences, play around with the settings in Mail Chimp and test it with some test users. You may be able to have 2 audiences for a single API key.

**Comment by parkerrobbins** [comment]
Thank you very much, @alexchippendale!

**Comment by alexchippendale** [comment]
No problem, @parkerrobbins !

**Comment by parkerrobbins** [comment]
Hi, @alexchippendale! I copied all of the settings from the original audience into the new audience, but the API import doesn't just work. Let me know how you would like me to communicate the Audience ID (e.g., an email address).

Thank you so much!

**Comment by alexchippendale** [comment]
@parkerrobbins Hey @parkerrobbins! Could you clarify a little bit what you mean by communicate the Audience ID? What isn't working with the new audience exactly? Thanks!

**Comment by parkerrobbins** [comment]
@alexchippendale Sure!

We would like to set up an API call to add new users to an _additional_ Mailchimp audience (i.e., to two audiences) when they first sign into the app. (Currently, the API call only adds users to one audience, so another will need to be set up for the second audience.) This Mailchimp audience has a unique identifier that needs to be passed in this new (second) API call. Does that clarify?

The number is sensitive information, so it shouldn't be transmitted over GitHub Issues. Please let me know how I can send it to you so it can be passed on to the developers.

**Comment by parkerrobbins** [comment]
@alexchippendale Following up. Thanks!

**Comment by alexchippendale** [comment]
Hey @parkerrobbins, I think you will be able get two separate mailing lists using Mailchimp 'segments'. This page from Mailchimp seems to have the info you're looking for: https://mailchimp.com/help/create-audience/

**Comment by alexchippendale** [comment]
@parkerrobbins Does a new person signing up receive both emails? Also see https://mailchimp.com/help/use-combine-audiences-tool/

You should be able to send out 2 emails on different schedules with the same audience. Are people opting into one but not the other? And if so how would they be doing that?

**Comment by parkerrobbins** [comment]
@alexchippendale I could look into doing it this way instead. Thanks for the tip. I'll let you know if this ends up working.

**Comment by jkhartshorne** [comment]
@parkerrobbins any luck?

**Comment by parkerrobbins** [comment]
@jkhartshorne It's slow-going. Not getting a lot of good information from Mailchimp's documentation or support team, but I have an interim solution that will allow us to only need to use one audience.

**Comment by parkerrobbins** [comment]
@jkhartshorne @alexchippendale 

Just an update: Adding new subscribers to the new Mailchimp groups is a manual process, but that's fine for now as there are only a few new contacts at a time.

Thanks, @alexchippendale, for pointing me to that resource above.
