### ISSUE TITLE
"Clear search" option for search

### ISSUE THREAD

**Issue by jkhartshorne** [kidtalkdev/KidTalkRemainingTasks#22]
To clear the search in the scrapbook, you have to search for an empty phrase and uncheck "clip/conversations/picture". People will work that out, but it's pretty clunky. Would it be simple to add a "clear search" button?

Not really a "remaining issue" or a "bug", so I just flipped a coin and put it here.

**Comment by alexchippendale** [comment]
Yes that could be useful. It may take a little longer for us to get to since we're busy with the others, but I'll let you know when we've added it and it's ready to test!

**Comment by alexchippendale** [comment]
@jkhartshorne This has been deployed to staging. We may update the styles next week to give it a bit more spacing, otherwise should work as expected.

**Comment by alexchippendale** [comment]
This should be deployed to production this week along with several other fixes or additions.

**Comment by jkhartshorne** [comment]
Is this up now, then?

**Comment by alexchippendale** [comment]
Yes this has been deployed to production!
