### ISSUE TITLE
Larger MB limit for upload?

### ISSUE THREAD

**Issue by jkhartshorne** [kidtalkdev/KidTalkRemainingTasks#24]
Now that we have the much faster processing, do you think we could try increasing the limit to maybe 500 MB?

**Comment by alexchippendale** [comment]
I will discuss this with the dev team to see if it's possible.

**Comment by alexchippendale** [comment]
@jkhartshorne Looks like this is possible. Will update you when it's been changed.

**Comment by alexchippendale** [comment]
@jkhartshorne This is now deployed to production.
