### ISSUE TITLE
Adding a favicon to kidtalk.app

### ISSUE THREAD

**Issue by parkerrobbins** [kidtalkdev/KidTalkRemainingTasks#25]
(@jkhartshorne @lorenachipstudio)

We would like to add this image as a favicon to kidtalk.app

![favicon](https://user-images.githubusercontent.com/31826170/93218489-466d0300-f738-11ea-8007-5d9d143202d3.png)

Please let me know if you have any questions.

Thanks!

**Comment by lorenachipstudio** [comment]
@parkerrobbins I'll let the team know to add it!

**Comment by alexchippendale** [comment]
We are working on adding this and it should be deployed to production this week.

**Comment by alexchippendale** [comment]
This has been deployed to production!

**Comment by parkerrobbins** [comment]
Thank you! I see it on the production site, but I don't see it on staging. Not sure if that was intentional, just an observation.
