### ISSUE TITLE
Scrapbook - No thumbnails for elicited conversations

### ISSUE THREAD

**Issue by alexchippendale** [kidtalkdev/KidTalkRemainingTasks#8]
Scrapbook - No thumbnails for elicited conversations

**Comment by alexchippendale** [comment]
This is currently in development.

**Comment by alexchippendale** [comment]
This should be deployed shortly.

**Comment by alexchippendale** [comment]
@jkhartshorne This has been deployed to staging:

<img width="306" alt="Screen Shot 2020-08-22 at 1 04 52 PM" src="https://user-images.githubusercontent.com/8966247/90964725-15224f80-e478-11ea-9d4e-b9bfd7156b77.png">

<img width="297" alt="Screen Shot 2020-08-22 at 1 05 26 PM" src="https://user-images.githubusercontent.com/8966247/90964733-28351f80-e478-11ea-9c28-e2a2c8f1fe73.png">

**Comment by jkhartshorne** [comment]
Yup, I see it!
