### ISSUE TITLE
Scrapbook - Doesn't look very much like the wireframes

### ISSUE THREAD

**Issue by alexchippendale** [kidtalkdev/KidTalkRemainingTasks#9]
Scrapbook - Doesn't look very much like the wireframes

**Comment by alexchippendale** [comment]
As the other scrapbook features are deployed and a couple styles are updated, this will appear more like the wireframes. This is currently in development.

**Comment by alexchippendale** [comment]
The newer changes have made the staging build look more like the wireframes:

<img width="325" alt="Screen Shot 2020-08-21 at 8 32 32 PM" src="https://user-images.githubusercontent.com/8966247/90947783-73562080-e3ed-11ea-8922-3bebe9c3348f.png">

<img width="312" alt="Screen Shot 2020-08-21 at 8 35 31 PM" src="https://user-images.githubusercontent.com/8966247/90947831-df388900-e3ed-11ea-980c-aab6ef0c7f4c.png">

**Comment by jkhartshorne** [comment]
I was actually also referring to what happens when you click on a box. Let's leave this open until those issues are finished.

**Comment by alexchippendale** [comment]
#1 and #2 are now deployed on staging.
